### ISSUE TITLE
Broken Multilevel sorting

### ISSUE THREAD

**Issue by TomazErjavec** [ufal/lindat-kontext#149]
Concordance / Sort / Multilevel sort with default setting produces on LINDAT:
```Failed to process your request. Please try again later or contact system support.```
and on CLARIN.SI:
```type object 'Kontext' has no attribute 'onelevelcrit'```

**Comment by kosarko** [comment]
seems to work with the current version of kontext@lindat. Can you verify and reopen the issue in case it's still broken?

**Comment by vidiecan** [comment]
working in the latest version

@TomazErjavec we have been fiercely working on the transition to version 0.12 and we are almost there, it is already running on our production. will announce it later this week

**Comment by TomazErjavec** [comment]
> @TomazErjavec we have been fiercely working on the transition to version 0.12 and we are almost there, it is already running on our production. will announce it later this week.

Great! Exactly when Bojan (with the help of two shell scripts that set permissions) managed to maybe fix

``` 
npm install && grunt production && PORT=5000 pm2 startOrRestart ecosystem.config.js
```
😀
